[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

# Configurazione form
[forms]
  [forms.contact]
    name = "contact"
    # Ricevi notifiche per email quando qualcuno compila il form
    [forms.contact.notifications]
      email = "riccardomartella77@gmail.com"
  
  [forms.contactit]
    name = "contactit"
    [forms.contactit.notifications]
      email = "riccardomartella77@gmail.com"

      [forms.reportbugen]
    name = "reportbugen"
    [forms.reportbugen.notifications]
      email = "riccardomartella77@gmail.com"

      [forms.reportbugit]
    name = "reportbugit"
    [forms.reportbugit.notifications]
      email = "riccardomartella77@gmail.com"

# Redirect dopo invio del form (opzionale)
[[redirects]]
  from = "/thankyou"
  to = "/"
  status = 302
